### PR TITLE
Performance, interface, unit tests, readability

### LINKED ISSUE #12: Fix indices order in read and write of the color matrix used to produce wavescapes
Issues spotted by @johentsch , in some parts of the code the Y and X axis are inverted to read and write colors in the matrix (examples [here ](https://github.com/DCMLab/wavescapes/blob/8203b6613ef32d9e5efa78cdaab73f05ad64558b/wavescapes/color.py#L192) and [here ](https://github.com/DCMLab/wavescapes/blob/8203b6613ef32d9e5efa78cdaab73f05ad64558b/wavescapes/draw.py#L262)). The inversion of those access indices are consistent along the whole library, so it does not cause any issue in the visualisation, but it sure does confuse code readers.

### PR DESCRIPTION
**Pull request by johentsch**
**Performance**

This is a first step to improve performance through vectorization, i.e. by avoiding to write elements into numpy arrays using (nested) for-loops. 

In particular, the creation of upper triangle matrices from the first row (`dft.build_utm_from_one_row()`) was sped up by factor 10 using `itertools.accumulate()`. This was the fastest (head to head with the iterative approach) of four tested approaches, here's the [perfplot](https://pypi.org/project/perfplot/) where `build_utm` is the previous solution with two nested for-loops:
perfplot_utm
Perfplot has tested the results of the kernels for equality so the new code can be trusted to give the same outputs.

**Interface**

The library was missing the possibility to pass your own pitch class vectors to `single_wavescape()` and to `all_wavescapes()` (they accept only file names). In order to keep their interface as it is, I've made them both use the new `single_wavescape_from_pcvs()` and `all_wavescapes_from_pcvs()`.

**Test notebook**

It contained tests on audio files that are not present. I've deactivated these parts and re-run the notebook. The last cell now prints the execution time.

**Readability**

closes #12 

As mentioned in the issue, it took a moment to understand the indexing although it certainly makes sense as it is. I've renamed the variables in the nested for-loops to `grouped_segments` for y (which should have been x) and `last_segment` for x (which should have been y). I also switched the variable names `shape_x`, `shape_y`, `utm_h`, `utm_w` although it doesn't really matter because we are always dealing with square matrices.

### CODE REVIEW

**Comment by robert-lieck** [comment]
I am not at all familiar with the code of this library, so cannot comment much on the code-level. But just from the description this all sounds very reasonable and solid (reasonable design decisions in term of naming and backwards compatibility and quantitatively backed performance descision with testing to ensure the output remains unchanged). Maybe @fabianmoss is more familiar with the code itself and can comment on that?

**Comment by fabianmoss** [comment]
Same here, I think @cedricviaccoz can best evaluate this.

**Comment by johentsch** [comment]
OK so here's the next part of the package with the main purpose of vectorizing the computations in the `color` module to avoid reading from and writing into arrays element-wise in nested for-loops. One major change that came along is that `circular_hue` now computes HTML colors directly rather than going from decimal RGB -> 8-bit RGB -> HTML. The conversion from hue -> decimal RGB, `step_function_quarter_pi_activation()`, was replaced by the equivalent and vectorized `matplotlib.color.hsv_to_rgb`.

The transition to the new code was done safely in three steps, reflected in the commit messages:
1. Add parameter `decimal` to `circular_hue()` and enable it to return decimal ('normalized') RGB. At the same time, establish the order `(magnitude, phase)` for variables for homogeneity with the `mag_phase` matrices (see below).
2. Add the alternative implementations in the separate file `test_color.py` that tests them against the current ones for all parameter combinations using decimal RGB as "common language".
3. Swap the function bodies between the files, have `complex_utm_to_ws_utm()` return HTML colors by default, and adapt the few places in `draw.py` where this changes the code. The tests are now parametrized using `pytest`.

And last but not least, I added a new option to (the newly factored out) `normalize_dft`, which served as the initial impulse for this suggested update. Let me know about any questions, comments, improvements, rejections on your side, @cedricviaccoz .

**Comment by johentsch** [comment]
@cedricviaccoz Could you please merge this and release a new version?

**Comment by cedricviaccoz** [comment]
The new version has been released: https://pypi.org/project/wavescapes/1.2.0/ much apologies for the time it took to do it.

**Comment by johentsch** [comment]
That's good news, thanks a lot!

**Pull request merged**
